export default {
   loginForm: {
       email: '',
       password: '',
   },
    loginFormValid: {
        email: false,
        password: false,
    },
    loginFormErrors: {
        email: '',
        password: '',
    },
    loginInvalid: false,
    errorLogin: '',
    registrationForm: {
        surname: '',
        name: '',
        patronymic: '',
        experience: '',
        post: '',
        region: '',
        district: '',
        typeOfArea: '',
        category: '',
        educationalOrganization : '',
        email : '',
        password : '',
    },
    registrationFormValid: {
        surname: false,
        name: false,
        patronymic: false,
        experience: false,
        post: false,
        region: false,
        district: false,
        typeOfArea: false,
        category: false,
        educationalOrganization : false,
        email : false,
        password : false,
    },
    registrationFormErrors: {
        surname: '',
        name: '',
        patronymic: '',
        experience: '',
        post: '',
        region: '',
        district: '',
        typeOfArea: '',
        category: '',
        educationalOrganization : '',
        email : '',
        password : '',
    },
    registrationInvalid: false,
    dataForRegistration: {
        experience: [],
        post: [],
        region: [],
        district: [],
        typeOfArea: [],
        category: [],
    },
}